Pablo Alejandro Aguirre Higuera

Matrícula: 263845

**Práctica #4. Manipulación de matrices**

22/08/2025

Creación de matrices

In [1]:
import numpy as np

A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

print("Matriz A:\n", A, "\n")
print("Matriz B:\n", B)

Matriz A:
 [[ 9  8 10]
 [ 5  9  5]
 [ 3  6  1]] 

Matriz B:
 [[10  8  3]
 [ 7 10  3]
 [ 1  9  5]]


1. Suma de matrices

In [2]:
print(A + B)

[[19 16 13]
 [12 19  8]
 [ 4 15  6]]


2. Resta de matrices

In [3]:
print(A - B)

[[-1  0  7]
 [-2 -1  2]
 [ 2 -3 -4]]


3. Multiplicación de una matriz por un escalar

In [4]:
print(A * 2)

[[18 16 20]
 [10 18 10]
 [ 6 12  2]]


4. Multiplicación de matrices

In [7]:
print(A @ B, "\n")

print(np.dot(A,B))

#Ambas formas funcionan

[[156 242 101]
 [118 175  67]
 [ 73  93  32]] 

[[156 242 101]
 [118 175  67]
 [ 73  93  32]]
